'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Aprobador

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LblUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GvActivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GvActivos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LblIdActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblIdActivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtIdActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtIdActivo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBuscar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LblNombreActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNombreActivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtNombreActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombreActivo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblTipoDeActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTipoDeActivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DdlTipoActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlTipoActivo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LblAños control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAños As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtAños control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAños As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFecha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFecha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Lblmensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lblmensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMontoCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMontoCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtMontoCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMontoCompra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblValorDesecho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorDesecho As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtValorDesecho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtValorDesecho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblIDEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblIDEmpleado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtIdEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtIdEmpleado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEstado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEstado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RbnAprovado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RbnAprovado As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RbnDenegado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RbnDenegado As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''BtnDepreciaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDepreciaciones As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GvDepreciaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GvDepreciaciones As Global.System.Web.UI.WebControls.GridView
End Class
